apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram
    receivers:
      - uid: rwmon-telegram
        type: telegram
        disableResolveMessage: false
        settings:
          bottoken: __TG_BOT_TOKEN__
          chatid: "__TG_CHAT_ID__"
          message_thread_id: "__TG_TOPIC_ID__"
          parse_mode: HTML
          disable_web_page_preview: true
          message: '{{ template "rwmon.message" . }}'
